### ISSUE TITLE
Logs grow indefinitely

### ISSUE THREAD

**Issue by jameshochadel** [cwru-hvz-core/cwru-hvz-source#55]
Production log grows without limit. Attempted to fix in commits 03e7578 and d035794, but did not succeed.

**Comment by tdooner** [comment]
The best fix to this is probably an operational-level one (e.g. logrotate) instead of an application one. Creating a single log file is probably a reasonable simple behavior. But if the logs are growing too quickly it might be because Rails is outputting more than necessary into them. In production, Rails should only output a single line per request. That should end up being only a few KB per game.

**Comment by jameshochadel** [comment]
Added configuration to /etc/logrotate.conf; logs will rotate weekly and be removed after a month.
